### import torch and make tensors

In [1]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

### Get shapes of tensors

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [ ]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


### Get specials tensors

In [ ]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
# tensor of size (3,4) random numbers between 0 and 10 not included 10
torch.randint(low=0, high=10, size=(3,4))

tensor([[4, 4, 2, 7],
        [3, 5, 8, 9],
        [4, 9, 0, 2]])

In [4]:
torch.rand(3, 4) #random values between zero and one 

tensor([[0.9789, 0.3656, 0.0333, 0.8028],
        [0.6582, 0.8747, 0.4812, 0.0797],
        [0.3033, 0.9525, 0.2699, 0.5729]])

In [6]:
torch.randn((3,4)) # random values according to normal distrubition

tensor([[-0.9423,  0.0727,  2.1559,  0.0377],
        [ 1.1510, -1.4774, -0.5621, -1.0320],
        [-0.7033, -1.0732,  1.7381, -0.9780]])

### transform from numpy array to tensor 

In [7]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
